//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMembers
    {
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public int Points { get; set; }
        public string PhoneNumber { get; set; }
        public string MemberAddress { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public int MemberStatus { get; set; }
    }
}
